### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by elliotvilhelm** [markchen8717/Gekko_Bot_Trading_Strategies#4]
`LSTM_MACD_RSI_V3.js` line number 95 should be `this.importNN` not `this.importNN()`\

```
uncaughtException TypeError: this.importNN is not a function
    at Base.strat.init (/Users/null/gekko/strategies/LSTM _MACD_RSI_V3.js:95:7)
    at Base.bound [as init] (/Users/null/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/Users/null/gekko/plugins/tradingAdvisor/baseTradingMethod.js:69:8)
    at Actor.setupStrategy (/Users/null/gekko/plugins/tradingAdvisor/tradingAdvisor.js:61:19)
    at Actor.bound [as setupStrategy] (/Users/null/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/Users/null/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/Users/null/gekko/core/pluginUtil.js:98:22)
    at /Users/null/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/Users/null/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/Users/null/gekko/node_modules/async/dist/async.js:1015:17)
```

**Comment by markchen8717** [comment]
Bug is fixed, thank you for the information!
